#!/bin/bash
#COLORES
A='\e[1;34m'
r='\e[1;31m'
v='\e[1;32m'
f='\e[1;35m'
azul='\e[1;36m'
b='\e[0m'
ac='\e[1;36m'
rs="\033[38;5;207m"
m='\033[35m'
g='\e[1;30m'
am='\033[33m'
v1="${b}\033[32m"
r1="${b}\033[31m"
data="$(pwd)/data"
command -v python2 > /dev/null 2>&1 || { sleep 0.5; echo >&2 -e "\n$v1[$b1*$v1]$b Instalando python2..."; pkg install python2 -y &>> /dev/null;sleep 0.5;}
if [[ "$(pwd)" == "${HOME}/BannerAxew"  ]]; then
	ruta="${HOME}/BannerAxew"
else
	ruta="$(pwd)"
fi
if [[ -e ${data} && -e "${data}/login.py" && -e "${data}/motd" && -e "${data}/bash.bashrc" ]]; then
	true
else
	echo "\n${b}[${r1}*${b}] Error, reinstalando herramienta...\n"
	cd ${ruta}/..
	rm -rf BannerAxew
	git clone https://github.com/Tweaky349/BannerAxew
        if [[ ! -e "BannerAxew" ]]; then
		echo -e "\n${b}[${r1}*${b}] Revisa tu conexion a internet\n"
		exit
	else
		cd BannerAxew
		bash start
	fi
fi

help() {
	sleep 0.0
	echo -e "${v1}Creditos:${r1} AxewB)${b}"
	echo
	echo -e "  - Personalizar Terminal"
	echo -e "    ./start --banner"
	echo
	echo -e "  - Eliminar Personalizacion"
	echo -e "    ./start --delete"
	echo
	echo -e "  - Discord"
	echo -e "    ./start --discord"
	echo
	echo -e "  - Mostrar Banner"
	echo -e "    ./start --show"
	echo
}
banner() {
	rm -rf $PREFIX/etc/bash.bashrc
	cp ${ruta}/data/bash.bashrc $PREFIX/etc
	rm -rf $PREFIX/etc/motd
	echo "python2 ${ruta}/data/login.py" >> $PREFIX/etc/bash.bashrc
	sed -i '/ruta = */d' ${ruta}/data/login.py
	sed -i "/os.system('sh ' */d" ${ruta}/data/login.py
	echo "ruta = '"${ruta}"/data'" >> ${ruta}/data/login.py
	echo "os.system('sh ' + ruta)" >> ${ruta}/data/login.py
}
delete() {
	rm -rf $PREFIX/etc/motd
	cp ${ruta}/data/motd $PREFIX/etc
	sed -i '/python2 */d' $PREFIX/etc/bash.bashrc
}
BannerAxew() {
	echo -e "${v1}░█████╗░██╗░░██╗███████╗░██╗░░░░░░░██╗"
	echo -e "██╔══██╗╚██╗██╔╝██╔════╝░██║░░██╗░░██║"
	echo -e "███████║░╚███╔╝░█████╗░░░╚██╗████╗██╔╝"
	echo -e "██╔══██║░██╔██╗░██╔══╝░░░░████╔═████║░"
	echo -e "██║░░██║██╔╝╚██╗███████╗░░╚██╔╝░╚██╔╝░"
	echo -e "╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░${b}"
}
BannerAxew
if [[ ! -z $1 ]]; then
	case $1 in
	"--banner")
		echo -e "${b}[${v1}+${b}]${r1} Iniciando${b} banner personalizado"
		sleep 5
		banner
		clear
		python2 ${ruta}/data/login.py
		echo -e "${b}[${v1}++${b}] Hecho\n"
	;;
	"--delete")
		echo -e "${b}[${v1}+${b}]${r1} Eliminando${b} banner personalizado"
		sleep 5
		delete
		clear
		cat ${ruta}/data/motd
		echo -e "${b}[${v1}++${b}] Hecho\n"

	;;
	"--discord")
		echo -e "${b}[${v1}+${b}] Discord: Axew#7015"
		sleep 2
		echo -e "${b}[${v1}++${b}] Hecho\n"
	;;
	"--show")
		python2 ${ruta}/data/login.py
	;;
	*)
		echo -e "${v1}Menu de ayuda"
		echo -e "${v1}Comando:${r1} ${1}${v1} invalido."
		help
	;;
	esac
else
	echo -e "${v1}Menu de ayuda"
	help
fi
